import type { Story } from './types.ts';

export const STORIES: Story[] = [
  // French
  {
    id: 'fr-story-cafe',
    title: 'Un matin au café',
    blurb: 'Anya commande son tout premier café en français…',
    language: 'fr-FR',
    level: 'A1',
    minutes: 4,
    thumbColor: 'butter',
    freeThisWeek: true,
  },
  {
    id: 'fr-story-umbrella',
    title: 'Le parapluie perdu',
    blurb: 'Un après-midi pluvieux, un inconnu très gentil…',
    language: 'fr-FR',
    level: 'A1',
    minutes: 5,
    thumbColor: 'sky',
  },
  {
    id: 'fr-story-market',
    title: 'Au marché du dimanche',
    blurb: "On goûte des fromages, on hésite, on rit beaucoup.",
    language: 'fr-FR',
    level: 'A2',
    minutes: 6,
    thumbColor: 'moss',
  },
  {
    id: 'fr-story-letter',
    title: 'Une lettre pour grand-mère',
    blurb: 'Émilie cherche les mots justes pour dire merci.',
    language: 'fr-FR',
    level: 'A2',
    minutes: 7,
    thumbColor: 'lilac',
  },
  {
    id: 'fr-story-train',
    title: 'Le train de minuit',
    blurb: "Un trajet, une rencontre, une ville qui s'éveille.",
    language: 'fr-FR',
    level: 'B1',
    minutes: 8,
    thumbColor: 'berry',
  },

  // Spanish
  {
    id: 'es-story-panaderia',
    title: 'Una mañana en la panadería',
    blurb: 'Marcos pide pan recién hecho por primera vez…',
    language: 'es-ES',
    level: 'A1',
    minutes: 4,
    thumbColor: 'butter',
    freeThisWeek: true,
  },
  {
    id: 'es-story-llaves',
    title: 'Las llaves perdidas',
    blurb: 'Un piso, dos vecinos, y una llave que aparece donde menos se espera.',
    language: 'es-ES',
    level: 'A1',
    minutes: 5,
    thumbColor: 'sky',
  },
  {
    id: 'es-story-mercado',
    title: 'En el mercado de los domingos',
    blurb: 'Aceitunas, naranjas y un vendedor que cuenta chistes.',
    language: 'es-ES',
    level: 'A2',
    minutes: 6,
    thumbColor: 'moss',
  },
  {
    id: 'es-story-carta',
    title: 'Una carta para la abuela',
    blurb: 'Sofía busca las palabras justas para dar las gracias.',
    language: 'es-ES',
    level: 'A2',
    minutes: 7,
    thumbColor: 'lilac',
  },

  // Italian
  {
    id: 'it-story-caffe',
    title: 'Un caffè a Trastevere',
    blurb: 'Un cappuccino, due amici, e una mattina di sole.',
    language: 'it-IT',
    level: 'A1',
    minutes: 4,
    thumbColor: 'butter',
    freeThisWeek: true,
  },
  {
    id: 'it-story-treno',
    title: 'Il treno per Firenze',
    blurb: 'Una conversazione che dura tutto il viaggio.',
    language: 'it-IT',
    level: 'A2',
    minutes: 6,
    thumbColor: 'sky',
  },

  // German
  {
    id: 'de-story-baeckerei',
    title: 'Frühstück bei der Bäckerei',
    blurb: 'Brötchen, Butter, und eine kleine Verwechslung.',
    language: 'de-DE',
    level: 'A1',
    minutes: 4,
    thumbColor: 'butter',
    freeThisWeek: true,
  },
  {
    id: 'de-story-park',
    title: 'Ein Spaziergang im Park',
    blurb: 'Herbstblätter, ein Hund, und ein freundliches Gespräch.',
    language: 'de-DE',
    level: 'A2',
    minutes: 5,
    thumbColor: 'moss',
  },

  // Portuguese
  {
    id: 'pt-story-praia',
    title: 'Uma manhã na praia',
    blurb: 'O sol, a areia, e um café gelado que muda o dia.',
    language: 'pt-BR',
    level: 'A1',
    minutes: 4,
    thumbColor: 'sky',
    freeThisWeek: true,
  },
  {
    id: 'pt-story-feira',
    title: 'A feira de domingo',
    blurb: 'Frutas frescas, conversas curtas, e uma receita nova.',
    language: 'pt-BR',
    level: 'A2',
    minutes: 6,
    thumbColor: 'butter',
  },

  // Dutch
  {
    id: 'nl-story-fiets',
    title: 'Een ritje door Amsterdam',
    blurb: 'Grachten, kasseien, en een onverwachte regenbui.',
    language: 'nl-NL',
    level: 'A1',
    minutes: 4,
    thumbColor: 'lilac',
    freeThisWeek: true,
  },

  // Polish
  {
    id: 'pl-story-rynek',
    title: 'Rynek w Krakowie',
    blurb: 'Gołębie, kawiarnia i pierwszy raz po polsku.',
    language: 'pl-PL',
    level: 'A1',
    minutes: 4,
    thumbColor: 'berry',
    freeThisWeek: true,
  },

  // Russian
  {
    id: 'ru-story-metro',
    title: 'Утро в метро',
    blurb: 'Холодное утро, тёплый кофе, и неожиданная встреча.',
    language: 'ru-RU',
    level: 'A1',
    minutes: 4,
    thumbColor: 'sky',
    freeThisWeek: true,
  },
  {
    id: 'ru-story-dacha',
    title: 'Выходные на даче',
    blurb: 'Чай, варенье, и долгий разговор с соседкой.',
    language: 'ru-RU',
    level: 'A2',
    minutes: 6,
    thumbColor: 'moss',
  },

  // Swedish
  {
    id: 'sv-story-fika',
    title: 'En fika i Stockholm',
    blurb: 'Kanelbullar, kaffe, och en lugn eftermiddag.',
    language: 'sv-SE',
    level: 'A1',
    minutes: 4,
    thumbColor: 'butter',
    freeThisWeek: true,
  },
  {
    id: 'sv-story-skog',
    title: 'En tur i skogen',
    blurb: 'Mossa, sol, och tystnad.',
    language: 'sv-SE',
    level: 'A2',
    minutes: 5,
    thumbColor: 'moss',
  },

  // Norwegian
  {
    id: 'no-story-fjord',
    title: 'Fjord om morgenen',
    blurb: 'Tåke over vannet og en gammel kaffekopp.',
    language: 'nb-NO',
    level: 'A1',
    minutes: 4,
    thumbColor: 'sky',
    freeThisWeek: true,
  },
  {
    id: 'no-story-hytte',
    title: 'En kveld på hytta',
    blurb: 'Peisen brenner, og noen forteller en gammel historie.',
    language: 'nb-NO',
    level: 'A2',
    minutes: 6,
    thumbColor: 'berry',
  },

  // Greek
  {
    id: 'el-story-taverna',
    title: 'Ένα δείπνο στην ταβέρνα',
    blurb: 'Ψωμί, ελιές, και πολλά γέλια.',
    language: 'el-GR',
    level: 'A1',
    minutes: 4,
    thumbColor: 'butter',
    freeThisWeek: true,
  },
  {
    id: 'el-story-nisi',
    title: 'Πρωί στο νησί',
    blurb: 'Καφές με θέα τη θάλασσα και ένας ηλικιωμένος ψαράς.',
    language: 'el-GR',
    level: 'A2',
    minutes: 5,
    thumbColor: 'sky',
  },

  // Turkish
  {
    id: 'tr-story-kahvalti',
    title: 'Pazar günü kahvaltı',
    blurb: 'Çay, peynir ve uzun bir sohbet.',
    language: 'tr-TR',
    level: 'A1',
    minutes: 4,
    thumbColor: 'butter',
    freeThisWeek: true,
  },
  {
    id: 'tr-story-carsi',
    title: 'Kapalı Çarşıda bir gün',
    blurb: 'Renkler, kokular ve dostane bir pazarlık.',
    language: 'tr-TR',
    level: 'A2',
    minutes: 6,
    thumbColor: 'berry',
  },

  // Indonesian
  {
    id: 'id-story-pasar',
    title: 'Pagi di pasar',
    blurb: 'Buah segar, bumbu, dan seorang pedagang yang ramah.',
    language: 'id-ID',
    level: 'A1',
    minutes: 4,
    thumbColor: 'butter',
    freeThisWeek: true,
  },
  {
    id: 'id-story-warung',
    title: 'Sore di warung kopi',
    blurb: 'Kopi tubruk, hujan rintik, dan obrolan panjang.',
    language: 'id-ID',
    level: 'A2',
    minutes: 5,
    thumbColor: 'sky',
  },
];
